# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'voiceCommandDatabase.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1096, 480)
        MainWindow.setStyleSheet("QToolTip\n"
"{\n"
"     border: 1px solid black;\n"
"     background-color: #ffa02f;\n"
"     padding: 1px;\n"
"     border-radius: 3px;\n"
"     opacity: 100;\n"
"}\n"
"\n"
"QWidget\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QTreeView, QListView\n"
"{\n"
"    background-color: silver;\n"
"    margin-left: 5px;\n"
"}\n"
"\n"
"QWidget:item:hover\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #ca0619);\n"
"    color: #000000;\n"
"}\n"
"\n"
"QWidget:item:selected\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QMenuBar::item\n"
"{\n"
"    background: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected\n"
"{\n"
"    background: transparent;\n"
"    border: 1px solid #ffaa00;\n"
"}\n"
"\n"
"QMenuBar::item:pressed\n"
"{\n"
"    background: #444;\n"
"    border: 1px solid #000;\n"
"    background-color: QLinearGradient(\n"
"        x1:0, y1:0,\n"
"        x2:0, y2:1,\n"
"        stop:1 #212121,\n"
"        stop:0.4 #343434/*,\n"
"        stop:0.2 #343434,\n"
"        stop:0.1 #ffaa00*/\n"
"    );\n"
"    margin-bottom:-1px;\n"
"    padding-bottom:1px;\n"
"}\n"
"\n"
"QMenu\n"
"{\n"
"    border: 1px solid #000;\n"
"}\n"
"\n"
"QMenu::item\n"
"{\n"
"    padding: 2px 20px 2px 20px;\n"
"}\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    color: #000000;\n"
"}\n"
"\n"
"QWidget:disabled\n"
"{\n"
"    color: #808080;\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QAbstractItemView\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0.1 #646464, stop: 1 #5d5d5d);\n"
"}\n"
"\n"
"QWidget:focus\n"
"{\n"
"    /*border: 1px solid darkgray;*/\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0 #646464, stop: 1 #5d5d5d);\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-width: 1px;\n"
"    border-color: #1e1e1e;\n"
"    border-style: solid;\n"
"    border-radius: 6;\n"
"    padding: 3px;\n"
"    font-size: 12px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    min-width: 40px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"}\n"
"\n"
"QComboBox\n"
"{\n"
"    selection-background-color: #ffaa00;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QComboBox:hover,QPushButton:hover\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"\n"
"QComboBox:on\n"
"{\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"    selection-background-color: #ffaa00;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    border: 2px solid darkgray;\n"
"    selection-background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 15px;\n"
"\n"
"     border-left-width: 0px;\n"
"     border-left-color: darkgray;\n"
"     border-left-style: solid; /* just a single line */\n"
"     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"     border-bottom-right-radius: 3px;\n"
" }\n"
"\n"
"QComboBox::down-arrow\n"
"{\n"
"     image: url(:/qss_icons/DarkOrange/down_arrow.png);\n"
"}\n"
"\n"
"QGroupBox\n"
"{\n"
"    border: 1px solid darkgray;\n"
"    margin-top: 10px;\n"
"}\n"
"\n"
"QGroupBox:focus\n"
"{\n"
"    border: 1px solid darkgray;\n"
"}\n"
"\n"
"QTextEdit:focus\n"
"{\n"
"    border: 1px solid darkgray;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"     border: 1px solid #222222;\n"
"     background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"     height: 7px;\n"
"     margin: 0px 16px 0 16px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"     subcontrol-position: left;\n"
"     subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::right-arrow:horizontal, QScrollBar::left-arrow:horizontal\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"      width: 7px;\n"
"      margin: 16px 0 16px 0;\n"
"      border: 1px solid #222222;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      height: 14px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #d7801a, stop: 1 #ffa02f);\n"
"      height: 14px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"}\n"
"\n"
"QPlainTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #616161, stop: 0.5 #505050, stop: 0.6 #434343, stop:1 #656565);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"}\n"
"\n"
"QCheckBox:disabled\n"
"{\n"
"color: #414141;\n"
"}\n"
"\n"
"QDockWidget::title\n"
"{\n"
"    text-align: center;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
"}\n"
"\n"
"QDockWidget::close-button, QDockWidget::float-button\n"
"{\n"
"    text-align: center;\n"
"    spacing: 1px; /* spacing between items in the tool bar */\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
"}\n"
"\n"
"QDockWidget::close-button:hover, QDockWidget::float-button:hover\n"
"{\n"
"    background: #242424;\n"
"}\n"
"\n"
"QDockWidget::close-button:pressed, QDockWidget::float-button:pressed\n"
"{\n"
"    padding: 1px -1px -1px 1px;\n"
"}\n"
"\n"
"QMainWindow::separator\n"
"{\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #4c4c4c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QMainWindow::separator:hover\n"
"{\n"
"\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #d7801a, stop:0.5 #b56c17 stop:1 #ffa02f);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QToolBar::handle\n"
"{\n"
"     spacing: 3px; /* spacing between items in the tool bar */\n"
"     background: url(:/qss_icons/DarkOrange/handle.png);\n"
"}\n"
"\n"
"QMenu::separator\n"
"{\n"
"    height: 2px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    margin-left: 10px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QProgressBar\n"
"{\n"
"    border: 2px solid grey;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk\n"
"{\n"
"    background-color: #d7801a;\n"
"    width: 2.15px;\n"
"    margin: 0.5px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    color: #b1b1b1;\n"
"    border: 1px solid #444;\n"
"    border-bottom-style: none;\n"
"    background-color: #323232;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    padding-top: 3px;\n"
"    padding-bottom: 2px;\n"
"    margin-right: -1px;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: 1px solid #444;\n"
"    top: 1px;\n"
"}\n"
"\n"
"QTabBar::tab:last\n"
"{\n"
"    margin-right: 0; /* the last selected tab has nothing to overlap with on the right */\n"
"    border-top-right-radius: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:first:!selected\n"
"{\n"
" margin-left: 0px; /* the last selected tab has nothing to overlap with on the right */\n"
"\n"
"\n"
"    border-top-left-radius: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected\n"
"{\n"
"    color: #b1b1b1;\n"
"    border-bottom-style: solid;\n"
"    margin-top: 3px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:.4 #343434);\n"
"}\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    margin-bottom: 0px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover\n"
"{\n"
"    /*border-top: 2px solid #ffaa00;\n"
"    padding-bottom: 3px;*/\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:0.4 #343434, stop:0.2 #343434, stop:0.1 #ffaa00);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked, QRadioButton::indicator:unchecked{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"    border: 1px solid #b1b1b1;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked\n"
"{\n"
"    background-color: qradialgradient(\n"
"        cx: 0.5, cy: 0.5,\n"
"        fx: 0.5, fy: 0.5,\n"
"        radius: 1.0,\n"
"        stop: 0.25 #ffaa00,\n"
"        stop: 0.3 #323232\n"
"    );\n"
"}\n"
"\n"
"QCheckBox::indicator{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"    border: 1px solid #b1b1b1;\n"
"    width: 9px;\n"
"    height: 9px;\n"
"}\n"
"\n"
"QRadioButton::indicator\n"
"{\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover, QCheckBox::indicator:hover\n"
"{\n"
"    border: 1px solid #ffaa00;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    image:url(:/qss_icons/DarkOrange/checkbox.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:disabled, QRadioButton::indicator:disabled\n"
"{\n"
"    border: 1px solid #444;\n"
"}\n"
"\n"
"\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid #3A3939;\n"
"    height: 8px;\n"
"    background: #201F1F;\n"
"    margin: 2px 0;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1,\n"
"      stop: 0.0 silver, stop: 0.2 #a8a8a8, stop: 1 #727272);\n"
"    border: 1px solid #3A3939;\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    margin: -4px 0;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border: 1px solid #3A3939;\n"
"    width: 8px;\n"
"    background: #201F1F;\n"
"    margin: 0 0px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 silver,\n"
"      stop: 0.2 #a8a8a8, stop: 1 #727272);\n"
"    border: 1px solid #3A3939;\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    margin: 0 -4px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QAbstractSpinBox {\n"
"    padding-top: 2px;\n"
"    padding-bottom: 2px;\n"
"    border: 1px solid darkgray;\n"
"\n"
"    border-radius: 2px;\n"
"    min-width: 50px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 20, 432, 311))
        self.frame.setStyleSheet("background-color:#ffa850;\n"
"border-style: solid;\n"
"border-width: 5px;\n"
"border-color: #556B2F;\n"
"border-radius: 5px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setStyleSheet("border-style: solid;\n"
"border-width: 3px;\n"
"background-color: #ffe5d8;")
        self.widget.setObjectName("widget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("background-color: #ff9b0f;\n"
"color: black;\n"
"border-color: #4d4018;")
        self.label.setObjectName("label")
        self.horizontalLayout_22.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(13, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem)
        self.radioButton = QtWidgets.QRadioButton(self.widget)
        self.radioButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton.setStyleSheet("QRadioButton{\n"
"    background-color: #ff6d49;\n"
"    color: black;;\n"
"    border-color: #4d4018;\n"
"}\n"
"\n"
"QRadioButton:hover{\n"
"    background-color: red;\n"
"}\n"
"")
        self.radioButton.setChecked(True)
        self.radioButton.setAutoExclusive(False)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_22.addWidget(self.radioButton)
        spacerItem1 = QtWidgets.QSpacerItem(88, 77, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_2.setStyleSheet("QRadioButton{\n"
"    background-color: #ff6d49;\n"
"    color: black;;\n"
"    border-color: #4d4018;\n"
"}\n"
"\n"
"QRadioButton:hover{\n"
"    background-color: red;\n"
"}\n"
"")
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setAutoExclusive(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_22.addWidget(self.radioButton_2)
        self.gridLayout_5.addLayout(self.horizontalLayout_22, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.widget)
        self.widget_3 = QtWidgets.QWidget(self.frame)
        self.widget_3.setStyleSheet("border-style: solid;\n"
"border-width: 3px;\n"
"background-color: #ffe5d8;")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setStyleSheet("background-color: #ff9b0f;\n"
"color: black;\n"
"border-color: #4d4018;")
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 0, 1, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.widget_3)
        self.radioButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_3.setStyleSheet("QRadioButton{\n"
"    background-color: #ff6d49;\n"
"    color: black;;\n"
"    border-color: #4d4018;\n"
"}\n"
"\n"
"QRadioButton:hover{\n"
"    background-color: red;\n"
"}\n"
"")
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setAutoExclusive(False)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout_4.addWidget(self.radioButton_3, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 0, 3, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.widget_3)
        self.radioButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_4.setStyleSheet("QRadioButton{\n"
"    background-color: #ff6d49;\n"
"    color: black;;\n"
"    border-color: #4d4018;\n"
"}\n"
"\n"
"QRadioButton:hover{\n"
"    background-color: red;\n"
"}\n"
"")
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setAutoExclusive(False)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout_4.addWidget(self.radioButton_4, 0, 4, 1, 1)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(self.frame)
        self.widget_2.setStyleSheet("border-style: solid;\n"
"border-width: 3px;\n"
"background-color: #ffe5d8;")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_18 = QtWidgets.QLabel(self.widget_2)
        self.label_18.setStyleSheet("background-color: #ff9b0f;\n"
"color: black;\n"
"border-color: #4d4018;")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_21.addWidget(self.label_18)
        self.gridLayout_3.addLayout(self.horizontalLayout_21, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.widget_2)
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setStyleSheet("QComboBox{\n"
"    background-color: #ff6d49;\n"
"    color: black;;\n"
"    border-color: #4d4018;\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    background-color: red;\n"
"}\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 0, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.widget_4 = QtWidgets.QWidget(self.frame)
        self.widget_4.setStyleSheet("border-style: solid;\n"
"border-width: 3px;\n"
"background-color: #ffe5d8;")
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_19 = QtWidgets.QLabel(self.widget_4)
        self.label_19.setStyleSheet("background-color: #ff9b0f;\n"
"color: black;\n"
"border-color: #4d4018;")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_27.addWidget(self.label_19)
        self.gridLayout_10.addLayout(self.horizontalLayout_27, 0, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget_4)
        self.comboBox_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_2.setStyleSheet("QComboBox{\n"
"    background-color: #ff6d49;\n"
"    color: black;;\n"
"    border-color: #4d4018;\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    background-color: red;\n"
"}\n"
"")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_10.addWidget(self.comboBox_2, 0, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(500, 20, 521, 311))
        self.frame_2.setStyleSheet("background-color:#ffa850;\n"
"border-style: solid;\n"
"border-width: 5px;\n"
"border-color: #556B2F;\n"
"border-radius: 5px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.frame_2)
        self.scrollArea_2.setStyleSheet("border-style: solid;\n"
"border-width: 2px;\n"
"background-color: #ffe5d8;")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 478, 425))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_6 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setMinimumSize(QtCore.QSize(200, 75))
        self.widget_6.setStyleSheet("border-style: solid;\n"
"border-width: 3px;\n"
"background-color: #ffe5d8;")
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.pushButton_12 = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_12.setStyleSheet("QPushButton {\n"
"border-style: solid;\n"
"border-width: 3px;\n"
"background-color: #ff6d49;\n"
"border-color: #4d4018;\n"
"color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: red;\n"
"    \n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_15.addWidget(self.pushButton_12)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_36 = QtWidgets.QLabel(self.widget_6)
        self.label_36.setStyleSheet("background-color: #ff9b0f;\n"
"color: black;\n"
"border-color: #4d4018;\n"
"")
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_16.addWidget(self.label_36)
        self.label_37 = QtWidgets.QLabel(self.widget_6)
        self.label_37.setStyleSheet("background-color: #ff9b0f;\n"
"color: black;\n"
"border-color: #4d4018;")
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_16.addWidget(self.label_37)
        self.label_38 = QtWidgets.QLabel(self.widget_6)
        self.label_38.setStyleSheet("background-color: #ff9b0f;\n"
"color: black;\n"
"border-color: #4d4018;")
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_16.addWidget(self.label_38)
        self.label_39 = QtWidgets.QLabel(self.widget_6)
        self.label_39.setStyleSheet("background-color: #ff9b0f;\n"
"color: black;\n"
"border-color: #4d4018;")
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_16.addWidget(self.label_39)
        self.progressBar_8 = QtWidgets.QProgressBar(self.widget_6)
        self.progressBar_8.setStyleSheet("background-color: black;\n"
"border-color: #4d4018;")
        self.progressBar_8.setProperty("value", 24)
        self.progressBar_8.setObjectName("progressBar_8")
        self.horizontalLayout_16.addWidget(self.progressBar_8)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_16)
        self.gridLayout_15.addLayout(self.horizontalLayout_15, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_6)
        self.widget_12 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_12.sizePolicy().hasHeightForWidth())
        self.widget_12.setSizePolicy(sizePolicy)
        self.widget_12.setMinimumSize(QtCore.QSize(200, 75))
        self.widget_12.setStyleSheet("border-style: solid;\n"
"border-width: 3px;\n"
"background-color: #ffe5d8;")
        self.widget_12.setObjectName("widget_12")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.widget_12)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.pushButton_13 = QtWidgets.QPushButton(self.widget_12)
        self.pushButton_13.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_13.setStyleSheet("QPushButton {\n"
"border-style: solid;\n"
"border-width: 3px;\n"
"background-color: #ff6d49;\n"
"border-color: #4d4018;\n"
"color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: red;\n"
"    \n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_17.addWidget(self.pushButton_13)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_40 = QtWidgets.QLabel(self.widget_12)
        self.label_40.setStyleSheet("background-color: #ff9b0f;\n"
"color: black;\n"
"border-color: #4d4018;\n"
"")
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_18.addWidget(self.label_40)
        self.label_41 = QtWidgets.QLabel(self.widget_12)
        self.label_41.setStyleSheet("background-color: #ff9b0f;\n"
"color: black;\n"
"border-color: #4d4018;")
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_18.addWidget(self.label_41)
        self.label_42 = QtWidgets.QLabel(self.widget_12)
        self.label_42.setStyleSheet("background-color: #ff9b0f;\n"
"color: black;\n"
"border-color: #4d4018;")
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_18.addWidget(self.label_42)
        self.label_43 = QtWidgets.QLabel(self.widget_12)
        self.label_43.setStyleSheet("background-color: #ff9b0f;\n"
"color: black;\n"
"border-color: #4d4018;")
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_18.addWidget(self.label_43)
        self.progressBar_9 = QtWidgets.QProgressBar(self.widget_12)
        self.progressBar_9.setStyleSheet("background-color: black;\n"
"border-color: #4d4018;")
        self.progressBar_9.setProperty("value", 24)
        self.progressBar_9.setObjectName("progressBar_9")
        self.horizontalLayout_18.addWidget(self.progressBar_9)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_18)
        self.gridLayout_16.addLayout(self.horizontalLayout_17, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_12)
        self.widget_13 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_13.sizePolicy().hasHeightForWidth())
        self.widget_13.setSizePolicy(sizePolicy)
        self.widget_13.setMinimumSize(QtCore.QSize(200, 75))
        self.widget_13.setStyleSheet("border-style: solid;\n"
"border-width: 3px;\n"
"background-color: #ffe5d8;")
        self.widget_13.setObjectName("widget_13")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.widget_13)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.pushButton_14 = QtWidgets.QPushButton(self.widget_13)
        self.pushButton_14.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_14.setStyleSheet("QPushButton {\n"
"border-style: solid;\n"
"border-width: 3px;\n"
"background-color: #ff6d49;\n"
"border-color: #4d4018;\n"
"color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: red;\n"
"    \n"
"}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_19.addWidget(self.pushButton_14)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_44 = QtWidgets.QLabel(self.widget_13)
        self.label_44.setStyleSheet("background-color: #ff9b0f;\n"
"color: black;\n"
"border-color: #4d4018;\n"
"")
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_20.addWidget(self.label_44)
        self.label_45 = QtWidgets.QLabel(self.widget_13)
        self.label_45.setStyleSheet("background-color: #ff9b0f;\n"
"color: black;\n"
"border-color: #4d4018;")
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_20.addWidget(self.label_45)
        self.label_46 = QtWidgets.QLabel(self.widget_13)
        self.label_46.setStyleSheet("background-color: #ff9b0f;\n"
"color: black;\n"
"border-color: #4d4018;")
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_20.addWidget(self.label_46)
        self.label_47 = QtWidgets.QLabel(self.widget_13)
        self.label_47.setStyleSheet("background-color: #ff9b0f;\n"
"color: black;\n"
"border-color: #4d4018;")
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_20.addWidget(self.label_47)
        self.progressBar_10 = QtWidgets.QProgressBar(self.widget_13)
        self.progressBar_10.setStyleSheet("background-color: black;\n"
"border-color: #4d4018;")
        self.progressBar_10.setProperty("value", 24)
        self.progressBar_10.setObjectName("progressBar_10")
        self.horizontalLayout_20.addWidget(self.progressBar_10)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_20)
        self.gridLayout_17.addLayout(self.horizontalLayout_19, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_13)
        self.widget_14 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_14.sizePolicy().hasHeightForWidth())
        self.widget_14.setSizePolicy(sizePolicy)
        self.widget_14.setMinimumSize(QtCore.QSize(200, 75))
        self.widget_14.setStyleSheet("border-style: solid;\n"
"border-width: 3px;\n"
"background-color: #ffe5d8;")
        self.widget_14.setObjectName("widget_14")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.widget_14)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.pushButton_15 = QtWidgets.QPushButton(self.widget_14)
        self.pushButton_15.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_15.setStyleSheet("QPushButton {\n"
"border-style: solid;\n"
"border-width: 3px;\n"
"background-color: #ff6d49;\n"
"border-color: #4d4018;\n"
"color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: red;\n"
"    \n"
"}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_23.addWidget(self.pushButton_15)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_48 = QtWidgets.QLabel(self.widget_14)
        self.label_48.setStyleSheet("background-color: #ff9b0f;\n"
"color: black;\n"
"border-color: #4d4018;\n"
"")
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_24.addWidget(self.label_48)
        self.label_49 = QtWidgets.QLabel(self.widget_14)
        self.label_49.setStyleSheet("background-color: #ff9b0f;\n"
"color: black;\n"
"border-color: #4d4018;")
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_24.addWidget(self.label_49)
        self.label_50 = QtWidgets.QLabel(self.widget_14)
        self.label_50.setStyleSheet("background-color: #ff9b0f;\n"
"color: black;\n"
"border-color: #4d4018;")
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_24.addWidget(self.label_50)
        self.label_51 = QtWidgets.QLabel(self.widget_14)
        self.label_51.setStyleSheet("background-color: #ff9b0f;\n"
"color: black;\n"
"border-color: #4d4018;")
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_24.addWidget(self.label_51)
        self.progressBar_11 = QtWidgets.QProgressBar(self.widget_14)
        self.progressBar_11.setStyleSheet("background-color: black;\n"
"border-color: #4d4018;")
        self.progressBar_11.setProperty("value", 24)
        self.progressBar_11.setObjectName("progressBar_11")
        self.horizontalLayout_24.addWidget(self.progressBar_11)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_24)
        self.gridLayout_18.addLayout(self.horizontalLayout_23, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_14)
        self.widget_15 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_15.sizePolicy().hasHeightForWidth())
        self.widget_15.setSizePolicy(sizePolicy)
        self.widget_15.setMinimumSize(QtCore.QSize(200, 75))
        self.widget_15.setStyleSheet("border-style: solid;\n"
"border-width: 3px;\n"
"background-color: #ffe5d8;")
        self.widget_15.setObjectName("widget_15")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.widget_15)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.pushButton_16 = QtWidgets.QPushButton(self.widget_15)
        self.pushButton_16.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_16.setStyleSheet("QPushButton {\n"
"border-style: solid;\n"
"border-width: 3px;\n"
"background-color: #ff6d49;\n"
"border-color: #4d4018;\n"
"color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: red;\n"
"    \n"
"}")
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_25.addWidget(self.pushButton_16)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_52 = QtWidgets.QLabel(self.widget_15)
        self.label_52.setStyleSheet("background-color: #ff9b0f;\n"
"color: black;\n"
"border-color: #4d4018;\n"
"")
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_26.addWidget(self.label_52)
        self.label_53 = QtWidgets.QLabel(self.widget_15)
        self.label_53.setStyleSheet("background-color: #ff9b0f;\n"
"color: black;\n"
"border-color: #4d4018;")
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_26.addWidget(self.label_53)
        self.label_54 = QtWidgets.QLabel(self.widget_15)
        self.label_54.setStyleSheet("background-color: #ff9b0f;\n"
"color: black;\n"
"border-color: #4d4018;")
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_26.addWidget(self.label_54)
        self.label_55 = QtWidgets.QLabel(self.widget_15)
        self.label_55.setStyleSheet("background-color: #ff9b0f;\n"
"color: black;\n"
"border-color: #4d4018;")
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_26.addWidget(self.label_55)
        self.progressBar_12 = QtWidgets.QProgressBar(self.widget_15)
        self.progressBar_12.setStyleSheet("background-color: black;\n"
"border-color: #4d4018;")
        self.progressBar_12.setProperty("value", 24)
        self.progressBar_12.setObjectName("progressBar_12")
        self.horizontalLayout_26.addWidget(self.progressBar_12)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_26)
        self.gridLayout_19.addLayout(self.horizontalLayout_25, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_15)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_7.addWidget(self.scrollArea_2, 1, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(30, 360, 521, 61))
        self.frame_3.setStyleSheet("background-color:#ffa850;\n"
"border-style: solid;\n"
"border-width: 5px;\n"
"border-color: #556B2F;\n"
"border-radius: 5px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"border-style: solid;\n"
"border-width: 3px;\n"
"background-color: #ff6d49;\n"
"border-color: #4d4018;\n"
"color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: red;\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: orange;\n"
"    \n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_8.addWidget(self.pushButton_7, 0, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"border-style: solid;\n"
"border-width: 3px;\n"
"background-color: #ff6d49;\n"
"border-color: #4d4018;\n"
"color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: red;\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: orange;\n"
"    \n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_8.addWidget(self.pushButton_8, 0, 1, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"border-style: solid;\n"
"border-width: 3px;\n"
"background-color: #ff6d49;\n"
"border-color: #4d4018;\n"
"color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: red;\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: orange;\n"
"    \n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_8.addWidget(self.pushButton_9, 0, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"border-style: solid;\n"
"border-width: 3px;\n"
"background-color: #ff6d49;\n"
"border-color: #4d4018;\n"
"color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: red;\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: orange;\n"
"    \n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_8.addWidget(self.pushButton_4, 0, 3, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.centralwidget)
        self.widget_5.setGeometry(QtCore.QRect(600, 360, 171, 61))
        self.widget_5.setStyleSheet("border-style: solid;\n"
"border-width: 3px;\n"
"background-color: #ffe5d8;\n"
"border-color: #556B2F;")
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_5)
        self.label_4.setStyleSheet("background-color: #ff9b0f;\n"
"color: black;\n"
"border-color: #4d4018;\n"
"border-style: solid;\n"
"border-width: 3px;")
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_5)
        self.label_5.setStyleSheet("background-color: #ff9b0f;\n"
"color: black;\n"
"border-color: #4d4018;")
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 0, 0, 1, 1)
        self.widget_7 = QtWidgets.QWidget(self.centralwidget)
        self.widget_7.setGeometry(QtCore.QRect(850, 360, 171, 61))
        self.widget_7.setStyleSheet("border-style: solid;\n"
"border-width: 3px;\n"
"background-color: #ffe5d8;\n"
"border-color: #556B2F;")
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_6 = QtWidgets.QLabel(self.widget_7)
        self.label_6.setStyleSheet("background-color: #ff9b0f;\n"
"color: black;\n"
"border-color: #4d4018;\n"
"border-style: solid;\n"
"border-width: 3px;")
        self.label_6.setObjectName("label_6")
        self.gridLayout_9.addWidget(self.label_6, 0, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_7)
        self.label_7.setStyleSheet("background-color: #ff9b0f;\n"
"color: black;\n"
"border-color: #4d4018;")
        self.label_7.setObjectName("label_7")
        self.gridLayout_9.addWidget(self.label_7, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem5, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1096, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Voice Language:"))
        self.radioButton.setText(_translate("MainWindow", "Turkish"))
        self.radioButton_2.setText(_translate("MainWindow", "English"))
        self.label_2.setText(_translate("MainWindow", "Voice Gender"))
        self.radioButton_3.setText(_translate("MainWindow", "Male"))
        self.radioButton_4.setText(_translate("MainWindow", "Female"))
        self.label_18.setText(_translate("MainWindow", "Name:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "All"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Yusuf"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Kaan"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Mehmet"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Dila"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Eylül"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Nursena"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Eren"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Barış"))
        self.comboBox.setItemText(9, _translate("MainWindow", "Emre"))
        self.comboBox.setItemText(10, _translate("MainWindow", "Emin"))
        self.label_19.setText(_translate("MainWindow", "Commend:"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "All"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Merhaba"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Araba"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Ev"))
        self.pushButton_12.setText(_translate("MainWindow", "Play"))
        self.label_36.setText(_translate("MainWindow", "Language"))
        self.label_37.setText(_translate("MainWindow", "Gender"))
        self.label_38.setText(_translate("MainWindow", "Name"))
        self.label_39.setText(_translate("MainWindow", "Voice Command"))
        self.pushButton_13.setText(_translate("MainWindow", "Play"))
        self.label_40.setText(_translate("MainWindow", "Language"))
        self.label_41.setText(_translate("MainWindow", "Gender"))
        self.label_42.setText(_translate("MainWindow", "Name"))
        self.label_43.setText(_translate("MainWindow", "Voice Command"))
        self.pushButton_14.setText(_translate("MainWindow", "Play"))
        self.label_44.setText(_translate("MainWindow", "Language"))
        self.label_45.setText(_translate("MainWindow", "Gender"))
        self.label_46.setText(_translate("MainWindow", "Name"))
        self.label_47.setText(_translate("MainWindow", "Voice Command"))
        self.pushButton_15.setText(_translate("MainWindow", "Play"))
        self.label_48.setText(_translate("MainWindow", "Language"))
        self.label_49.setText(_translate("MainWindow", "Gender"))
        self.label_50.setText(_translate("MainWindow", "Name"))
        self.label_51.setText(_translate("MainWindow", "Voice Command"))
        self.pushButton_16.setText(_translate("MainWindow", "Play"))
        self.label_52.setText(_translate("MainWindow", "Language"))
        self.label_53.setText(_translate("MainWindow", "Gender"))
        self.label_54.setText(_translate("MainWindow", "Name"))
        self.label_55.setText(_translate("MainWindow", "Voice Command"))
        self.pushButton_7.setText(_translate("MainWindow", "Filter Data"))
        self.pushButton_8.setText(_translate("MainWindow", "Show All Data"))
        self.pushButton_9.setText(_translate("MainWindow", "Download Data"))
        self.pushButton_4.setText(_translate("MainWindow", "Clear Data"))
        self.label_4.setText(_translate("MainWindow", "22"))
        self.label_5.setText(_translate("MainWindow", "Showed Data:"))
        self.label_6.setText(_translate("MainWindow", "500"))
        self.label_7.setText(_translate("MainWindow", "All Data:"))
